api/urls.py
from django.urls import path
from rest_framework import routers

from api.apps import ApiConfig
from api.views import CartRetrieveAPIView, ItemViewSet, CartListAPIView

app_name = ApiConfig.name


router = routers.DefaultRouter()
router.register(r"item", ItemViewSet, basename="item")


urlpatterns = [
    path("cart/<int:pk>/", CartRetrieveAPIView.as_view(), name="cart"),
    path("all_carts/", CartListAPIView.as_view(), name="all_carts"),
] + router.urls

cart/urls.py
from django.urls import path

from cart.apps import CartConfig
from cart.views import (
    CanceledTemplateView,
    ConfirmPayment,
    OrdersListView,
    SuccessTemplateView,
)

app_name = CartConfig.name

urlpatterns = [
    path("order/", OrdersListView.as_view(), name="order"),
    path("confirm/", ConfirmPayment.as_view(), name="confirm"),
    path("order-success/", SuccessTemplateView.as_view(), name="order_success"),
    path("order_cancel/", CanceledTemplateView.as_view(), name="order_cancel"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from cart.views import stripe_webhook_view

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("user/", include("users.urls", namespace="user")),
    path("api/", include("api.urls")),
    path("stripe_webhooks", stripe_webhook_view, name="stripe_webhook"),
    path(
        "docs/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

cart/models.py
from django.core.validators import MaxValueValidator
from django.db import models

from shop.models import Item
from users.models import NULLABLE, User


# Create your models here.
class Order(models.Model):
    """Модель для корзины"""

    product = models.ForeignKey(
        to=Item, on_delete=models.CASCADE, related_name="product"
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name="количество")
    discount = models.ForeignKey(
        to="Discount", on_delete=models.CASCADE, related_name="discounts", **NULLABLE
    )
    tax = models.ForeignKey(
        to="Tax", on_delete=models.CASCADE, related_name="tax", **NULLABLE
    )
    stripe_id = models.CharField(
        max_length=128, verbose_name="id платежа на stripe", **NULLABLE
    )
    status = models.BooleanField(default=False, verbose_name="статус платежа")
    order_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.product)

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"


class Discount(models.Model):
    """Модель для скидки"""

    percent = models.PositiveIntegerField(
        default=0, validators=[MaxValueValidator(100)]
    )

    def __str__(self):
        return str(self.percent)

    class Meta:
        verbose_name = "скидка"
        verbose_name_plural = "скидки"


class Tax(models.Model):
    """Модель для налога"""

    tax_name = models.TextField(**NULLABLE, verbose_name="наименование налога")
    tax_percent = models.PositiveIntegerField(
        default=0, validators=[MaxValueValidator(100)]
    )

    def __str__(self):
        return self.tax_name

    class Meta:
        verbose_name = "налог"
        verbose_name_plural = "налоги"

cart/forms.py
from django.forms import ModelForm

from cart.models import Order
from shop.forms import StyleFormMixin


class CartForm(StyleFormMixin, ModelForm):
    """Форма для корзины"""

    class Meta:
        model = Order
        fields = "__all__"

cart/views.py
from http import HTTPStatus

import stripe
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from cart.forms import CartForm
from cart.models import Order
from config.settings import DOMAIN_NAME, STRIPE_WEBHOOK_KEY


class SuccessTemplateView(TemplateView):
    template_name = "cart/success_order.html"
    title = " Спасибо за заказ!"


class OrderTemplateView(TemplateView):
    template_name = "cart/order_form.html"


class CanceledTemplateView(TemplateView):
    template_name = "cart/canceled.html"


class OrdersListView(generic.ListView):
    """Просмотр заказов"""

    model = Order
    form_class = CartForm
    success_url = reverse_lazy("/")

    template_name = "cart/cart_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Order.objects.filter(user=self.request.user, status=False)
        if cart.exists():
            context["object_list"] = cart
        return context


class ConfirmPayment(generic.CreateView):
    model = Order
    form_class = CartForm
    success_url = reverse_lazy("/")

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        price = request.POST.get("stripe_price_id")
        quantity = request.POST.get("quantity")
        session = stripe.checkout.Session.create(
            success_url=DOMAIN_NAME + reverse("cart:order_success"),
            line_items=[{"price": price, "quantity": quantity}],
            mode="payment",
            metadata={"payment_id": request.POST.get("id")},
        )
        return HttpResponseRedirect(session.url, status=HTTPStatus.SEE_OTHER)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    event = None
    try:
        event = stripe.Webhook.construct_event(payload, sig_header, STRIPE_WEBHOOK_KEY)
    except ValueError:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        return HttpResponse(status=400)
    if event["type"] == "checkout.session.completed":
        session = stripe.checkout.Session.retrieve(event["data"]["object"]["id"])
        fulfill_order(session)

    return HttpResponse(status=200)


def fulfill_order(session):
    payment_id = int(session.metadata.payment_id)
    payment = Order.objects.get(pk=payment_id)
    payment.status = True
    payment.stripe_id = session.stripe_id
    payment.save()

cart/templates/cart/canceled.html
{% extends 'shop/base.html' %}
{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-body text-center">
                            <h4>
                                Произошла ошибка при оплате товара.
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

cart/templates/cart/cart_list.html
{% extends 'shop/base.html' %}
{% block content %}
{% load my_tags %}
    <section>
        <div class="container">
            <div class="py-2 text-center">
                <h1>Оформление заказа:</h1>
            </div>
            <div class="row g-7">
                <div class="col-md-7 col-lg-7 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-center">Корзина:</span>
                    </h4>
                    {% for object in object_list %}
                       <form method="post" action="{% url 'cart:confirm' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="hidden" name="id" value="{{ object.id }}">
                        <input type="hidden" name="stripe_price_id" value="{{ object.product.stripe_price_id }}">
                        <input type="hidden" name="quantity" value="{{ object.quantity }}">
                        <ul class="list-group mb-3">
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ object.product.name }}</h6>
                                    <small class="text-muted">{{ object.quantity }} шт.</small>
                                </div>
                                <span class="text-muted">Сумма к оплате: {% total_amount object.pk %} {{ object.product.currency }}.</span>
                                {% if object.status %}
                                    <a>Оплачен</a>
                                {% else %}
                                <button type="submit" class="btn btn-outline-light">Оформить заказ</button>
                                {% endif %}
                            </li>
                        </ul>
                       </form>
                        {% endfor %}


                </div>
            </div>
        </div>
    </section>

{% endblock content %}

cart/templates/cart/success_order.html
{% extends 'shop/base.html' %}
{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>
                                Вы успешно оплатили заказ!
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}