api/urls.py
from django.urls import path
from rest_framework import routers

from api.apps import ApiConfig
from api.views import CartRetrieveAPIView, ItemViewSet, CartListAPIView

app_name = ApiConfig.name


router = routers.DefaultRouter()
router.register(r"item", ItemViewSet, basename="item")


urlpatterns = [
    path("cart/<int:pk>/", CartRetrieveAPIView.as_view(), name="cart"),
    path("all_carts/", CartListAPIView.as_view(), name="all_carts"),
] + router.urls

cart/urls.py
from django.urls import path

from cart.apps import CartConfig
from cart.views import (
    CanceledTemplateView,
    ConfirmPayment,
    OrdersListView,
    SuccessTemplateView,
)

app_name = CartConfig.name

urlpatterns = [
    path("order/", OrdersListView.as_view(), name="order"),
    path("confirm/", ConfirmPayment.as_view(), name="confirm"),
    path("order-success/", SuccessTemplateView.as_view(), name="order_success"),
    path("order_cancel/", CanceledTemplateView.as_view(), name="order_cancel"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from cart.views import stripe_webhook_view

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("user/", include("users.urls", namespace="user")),
    path("api/", include("api.urls")),
    path("stripe_webhooks", stripe_webhook_view, name="stripe_webhook"),
    path(
        "docs/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

shop/urls.py
from django.urls import path

from shop.apps import ShopConfig
from shop.views import BuyItemView, ListItem, RetrieveItem

app_name = ShopConfig.name

urlpatterns = [
    path("", ListItem.as_view(), name="items"),
    path("item/<int:pk>", RetrieveItem.as_view(), name="item_details"),
    path("buy/<int:pk>", BuyItemView.as_view(), name="buy_item"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views
from users.apps import UserConfig
from users.views import UserLogIn

app_name = UserConfig.name


urlpatterns = [
    path("login/", UserLogIn.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout", kwargs={"next_page": "/"}),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("new_password/", views.generate_new_password, name="new_password"),
]

shop/models.py
import stripe
from django.db import models

from config.settings import STRIPE_SECRET_KEY
from users.models import NULLABLE

stripe.api_key = STRIPE_SECRET_KEY


class Item(models.Model):
    """Модель для товара"""

    currency = {
        ("USD", "USD"),
        ("RUB", "RUB"),
    }
    name = models.CharField(max_length=255, verbose_name="название")
    description = models.TextField(verbose_name="описание", **NULLABLE)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="цена")
    currency = models.CharField(max_length=3, choices=currency, verbose_name="валюта")
    stripe_price_id = models.CharField(max_length=128, **NULLABLE)

    def __str__(self):
        return self.name

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.stripe_price_id:
            stripe_product_price = self.product_create_stripe()
            self.stripe_price_id = stripe_product_price["id"]
        return super().save(
            force_insert=False, force_update=False, using=None, update_fields=None
        )

    def product_create_stripe(self):
        stripe_product = stripe.Product.create(name=self.name)

        stripe_product_price = stripe.Price.create(
            product=stripe_product["id"],
            currency=self.currency,
            unit_amount=round(self.price * 100),
        )
        return stripe_product_price

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"

shop/forms.py
from django import forms

from shop.models import Item


class StyleFormMixin:
    """Form stylization"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ItemForm(StyleFormMixin, forms.ModelForm):
    """Форма для модели Item"""

    class Meta:
        model = Item
        fields = "__all__"

shop/views.py
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.views import View, generic

from cart.forms import CartForm
from cart.models import Order
from shop.models import Item


class ListItem(generic.ListView):
    """Список Item'ов"""

    model = Item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = Item.objects.all()
        return context


class RetrieveItem(generic.DetailView):
    """Получение конкретного обьекта"""

    model = Item
    form_class = CartForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Formset = inlineformset_factory(Item, Order, form=CartForm, extra=1)
        context["formset"] = Formset(instance=self.object)
        context["object_list"] = Item.objects.filter(pk=self.object.pk)
        return context


class BuyItemView(View):
    """Добавление товара в корзину"""

    def post(self, request, pk):
        quantity_value = request.POST.get("quantity", "1")
        product = get_object_or_404(Item, pk=pk)
        Order.objects.create(
            product=product, quantity=int(quantity_value), user=self.request.user
        )
        return redirect("cart:order")

shop/templates/shop/base.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">


    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/pricing/">



    <link rel="stylesheet" href="{% static 'css/css@3.css' %}">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        {% if not user.is_authenticated %}
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'shop:items' %}">Главная</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'user:login' %}">Войти</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'user:register' %}">Зарегистрироваться</a>
        {% else %}
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" > {{ user }}</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'shop:items' %}">Главная</a>
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'cart:order' %}">Корзина</a>
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'user:logout' %}">Выйти</a>
        {% endif %}
      </nav>
    </div>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Somestore</h1>
    </div>
  </header>
  <main>
                {% block content %}
                {% endblock content %}

  </main>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

shop/templates/shop/item_detail.html
{% extends 'shop/base.html' %}
{% block content %}
{% for object in object_list %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card_header">
                            <h3 class="card-title pricing-card-title">{{ object.name }}</h3>
                            <h3 class="card-title pricing-card-title">{{ object.price }} {{ object.currency }}</h3>
                        </div>
                        <div class="card-body">
                            <h4 class="card-title pricing-card-title">{{ object.description }}</h4>
                        </div>
                        <div class="col-6">

                            <form method="POST" action="{% url 'shop:buy_item' object.pk %}">
                                {% csrf_token %}
                               Выбрать количество: <input type="text" name="quantity" >
                                <input type="submit" value="Оформить покупку">
                            </form>
                        </div>

                </div>
            </div>
        </div>
    </div>

{% endfor %}
{% endblock %}

shop/templates/shop/item_list.html
{% extends 'shop/base.html' %}
{% block content %}
{% for object in object_list %}

  <div class="row">
        <div class="col-12">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.name }} </h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ object.price }}({{ object.currency}})<small class="text-body-secondary fw-light"></small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ object.description }}</li>
                </ul>
                <div class="d-grid gap-2 d-md-block">
                    {% if not user.is_authenticated %}
                        <a>Для покупки необходимо авторизоваться</a>
                    {% else %}
                        <a class="btn btn-outline-light" href="{% url 'shop:item_details' object.pk %}" type="button"> Купить </a>
                    {% endif %}
                </div>
              </div>
            </div>
        </div>
  </div>


{% endfor %}
{% endblock content %}